### ISSUE TITLE
Add GitHub to Linux 

### ISSUE THREAD

**Issue by XueSongMa** [MKR-GDC/MSDEV-BDPOC#3]
Help to check how to add github to Linux side.

**Comment by XueSongMa** [comment]
@kzhang2017 @chuchu156  no open issues for this one, right? close it.

**Comment by XueSongMa** [comment]
@kzhang2017 @chuchu156 no open issues for this one, right? close it.

**Comment by kzhang2017** [comment]
Yes, task is done. Close it.
